libreria/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .views import Home, HomeSinPrivilegios, \
    AutoresNew, AutoresEdit, AutoresDel, \
    CatgeoriasNew, CategoriaEdit, CategoriaDel, \
        LibrosNew, LibrosEdit, LibrosDel, \
            LibrosPorAutorNew, LibrosPorAutorEdit, LibrosPorAutorDel, \
                ClientesNew, ClientesEdit, ClientesDel

urlpatterns = [
    path('', Home.as_view(), name="home"),
    path('sin_privilegios/',HomeSinPrivilegios.as_view(),name='sin_privilegios'),

    # Urls de acceso
    path('login/',auth_views.LoginView.as_view(template_name='cuentas/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='cuentas/login.html'),name='logout'),
    path('cambiar-contraseña/', auth_views.PasswordChangeView.as_view(template_name='cuentas/cambiar.html'), name='cambiar_contraseña'),
    path('cambiar-contraseña/completo/', auth_views.PasswordChangeDoneView.as_view(template_name='cuentas/cambiado.html'), name='cambiado'),

    # Urls libreria
    # Urls Autores
    path('autores/', views.listar_autores, name="autores"),
    path('autores/new/', AutoresNew.as_view(), name="autores_new"),
    path('autores/edit/<pk>', AutoresEdit.as_view(), name="autores_edit"),
    path('autores/delete/<pk>', AutoresDel.as_view(), name="autores_delete"),

    # Urls de libros
    path('libros/', views.listar_libros, name="libros"),
    path('libros/new/', LibrosNew.as_view(), name="libros_new"),
    path('libros/edit/<int:pk>', LibrosEdit.as_view(), name="libros_edit"),
    path('libros/delete/<int:pk>', LibrosDel.as_view(), name="libros_delete"),

    # Urls Categorias
    path('categorias/', views.listar_categorias, name="categorias"),
    path('categorias/new/', views.CatgeoriasNew.as_view(), name="categorias_new"),
    path('categorias/edit/<pk>', views.CategoriaEdit.as_view(), name="categorias_edit"),
    path('categorias/delete/<pk>', views.CategoriaDel.as_view(), name="categorias_delete"),

    # Urls Libros Por Autor
    path('libroXautor/', views.listar_libros_por_autor, name="libros_por_autor"),
    path('libroXautor/new/', LibrosPorAutorNew.as_view(), name="libros_por_autor_new"),
    path('libroXautor/edit/<pk>', LibrosPorAutorEdit.as_view(), name="libros_por_autor_edit"),
    path('libroXautor/delete/<pk>', LibrosPorAutorDel.as_view(), name="libros_por_autor_delete"),

    # Urls clients
    path('clientes/', views.listar_clientes, name="clientes"),
    path('clientes/new', ClientesNew.as_view(), name="clientes_new"),
    path('clientes/edit/<int:pk>', ClientesEdit.as_view(), name="clientes_edit"),
    path('clientes/delete/<int:pk>', ClientesDel.as_view(), name="clientes_delete"),

    
    path('pedidos_clientes/', views.listar_pedidos_clientes, name="pedidos_cliente"),


    # Carro de compras
    path('carro/add/<isbn>/', views.cart_add, name='cart_add'),
    path('carro/item_clear/<isbn>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<isbn>/',views.item_increment, name='item_increment'),
    path('cart/item_decrement/<isbn>/',views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('carro/cart-detail/',views.cart_detail, name='cart_detail')
]

prjaprendizjbhm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('libreria.urls','lib'), namespace='lib')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

libreria/models.py
from django.db import models

from django.contrib.auth.models import User

class Autores(models.Model):
    id_autor = models.IntegerField(primary_key=True)
    apellidos = models.CharField(max_length=25)
    nombres = models.CharField(max_length=25)

    def __str__(self):
        return '{} - {} {}'.format(
            self.id_autor,
            self.apellidos,
            self.nombres
        )
    
    def save(self):
        self.apellidos = self.apellidos.title()
        self.nombres = self.nombres.title()
        super(Autores, self).save()

    class Meta:
        db_table = 'autores'
        verbose_name_plural = "Autores"


class Categorias(models.Model):
    id_categoria = models.AutoField(primary_key=True)
    categoria = models.CharField(max_length=40)

    def __str__(self):
        return '{} - {}'.format(
            self.id_categoria,
            self.categoria
        )
    
    def save(self):
        self.categoria = self.categoria.capitalize()
        super(Categorias, self).save()

    class Meta:
        db_table = 'categorias'
        verbose_name_plural = "Categorias"


class Clientes(models.Model):
    id_clientes = models.AutoField(primary_key=True)
    identificacion = models.CharField(max_length=12, unique=True)
    nombres = models.CharField(max_length=25)
    apellidos = models.CharField(max_length=25)
    telefono = models.CharField(max_length=12)
    direccion = models.CharField(max_length=128, blank=True, null=True)
    correo_electronico = models.CharField(max_length=128, blank=True, null=True)

    def __str__(self):
        return '{} - {} - {} - {} - {} - {} - {}'.format( 
            self.id_clientes,
            self.identificacion,
            self.nombres,
            self.apellidos,
            self.telefono,
            self.direccion,
            self.correo_electronico
        )

    def save(self):
        self.apellidos = self.apellidos.title()
        self.nombres = self.nombres.title()
        super(Clientes, self).save()

    class Meta:
        db_table = 'clientes'
        verbose_name_plural = "Clientes"


class Libros(models.Model):
    isbn = models.IntegerField(primary_key=True)
    titulo = models.CharField(max_length=128)
    fecha_pub = models.DateField()
    categoria = models.ForeignKey(Categorias, db_column='categoria', on_delete=models.CASCADE)
    precio = models.IntegerField()
    portada = models.ImageField(blank=True, null=True, upload_to="portadas")

    def __str__(self):
        return '{} - {} - {} - {} - {} - {}'.format(
            self.isbn,
            self.titulo,
            self.fecha_pub,
            self.categoria,
            self.precio,
            self.portada
        )
    
    def save(self):
        self.titulo = self.titulo.capitalize()
        super(Libros, self).save()

    class Meta:
        db_table = 'libros'
        verbose_name_plural = "Libros"


class LibrosPorAutor(models.Model):
    id_autor = models.OneToOneField(Autores, db_column='id_autor', on_delete=models.CASCADE, primary_key=True)
    isbn = models.ForeignKey(Libros, db_column='isbn', on_delete=models.CASCADE)

    def __str__(self):
        return '{} - {}'.format(
            self.id_autor,
            self.isbn
        )

    class Meta:
        db_table = 'libros_por_autor'
        verbose_name_plural = "Libros Por Autores"


class PedidosCliente(models.Model):
    nro_pedido = models.AutoField(primary_key=True)
    id_cliente = models.ForeignKey(Clientes, db_column='id_cliente', on_delete=models.CASCADE)
    isbn = models.ForeignKey(Libros, db_column='isbn', on_delete=models.CASCADE)
    fecha_pedido = models.DateField(auto_now_add=True)
    cantidad = models.IntegerField()
    valor = models.IntegerField()

    def __str__(self):
        return '{} - {} - {} - {} - {} - {}'.format( 
            self.nro_pedido,
            self.id_cliente.nombres + self.id_cliente.apellidos,
            self.isbn.titulo,
            self.fecha_pedido,
            self.cantidad,
            self.valor,
        )

    class Meta:
        db_table = 'pedidos_cliente'
        verbose_name_plural = "Pedidos Por Clientes"

libreria/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from .models import Autores, Categorias, Clientes, Libros, \
    LibrosPorAutor, PedidosCliente
from .forms import AutoresForm, CategoriasForm, LibrosForm, \
    LibrosPorAutorForm, ClientesForm
from django.db.models import Q

# Decoradores
from django.contrib.auth.decorators import login_required, permission_required

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin

from .cart import Cart


class Sinprivilegios(SuccessMessageMixin, LoginRequiredMixin, \
    PermissionRequiredMixin):
    login_url = 'lib:login'
    raise_exception = False
    redirect_field_name = "redirecto_to"

    def handle_no_permission(self):
        from django.contrib.auth.models import AnonymousUser
        if not self.request.user==AnonymousUser():
            self.login_url='lib:sin_privilegios'
        return HttpResponseRedirect(reverse_lazy(self.login_url))


class Home(generic.TemplateView):
    template_name = 'libreria/index.html'


class HomeSinPrivilegios(generic.TemplateView):
    template_name = "libreria/sin_privilegios.html"


def listar_autores(request):
    busqueda = request.POST.get("buscar")
    autores = Autores.objects.all()

    if busqueda:
        autores = Autores.objects.filter(
            Q(id_autor__icontains = busqueda) | 
            Q(apellidos__icontains = busqueda) |
            Q(nombres__icontains = busqueda) 
        ).distinct()
         
    return render(request, 'libreria/autores_list.html', {'autores':autores})


class AutoresNew(Sinprivilegios, generic.CreateView):
    permission_required = "libreria.add_autores"
    model = Autores
    template_name = "libreria/autores_form.html"
    context_object_name = "obj"
    form_class = AutoresForm
    success_url = reverse_lazy('lib:autores')
    success_message = "Autor Creado Satisfactoriamente"


class AutoresEdit(Sinprivilegios, generic.UpdateView):
    permission_required = "libreria.change_autores"
    model = Autores
    temlate_name = "libreria/autores_form.html"
    context_object_name = "obj"
    form_class = AutoresForm
    success_url = reverse_lazy('lib:autores')
    success_message = "Autor Actualizado Satisfactoriamente"


class AutoresDel(Sinprivilegios, generic.DeleteView):
    permission_required = "libreria.delete_autores"
    model = Autores
    template_name = "libreria/libreria_del.html"
    context_object_name = "obj"
    success_url = reverse_lazy('lib:autores')
    success_message = "Autor Eliminado Satisfactoriamente"


def listar_libros(request):
    busqueda = request.POST.get("buscar")
    libros = Libros.objects.all()

    if busqueda:
        libros = Libros.objects.filter(
            Q(isbn__icontains = busqueda) | 
            Q(titulo__icontains = busqueda) |
            Q(fecha_pub__icontains = busqueda) |
            # Q(categoria__exact = busqueda) |
            Q(precio__icontains = busqueda) 
        ).distinct()
         
    return render(request, 'libreria/libros_list.html', {'libros':libros})

class LibrosNew(Sinprivilegios, generic.CreateView):
    permission_required = "libreria.add_libros"
    model = Libros
    template_name = "libreria/libros_form.html"
    context_object_name = "obj"
    form_class = LibrosForm
    success_url = reverse_lazy('lib:libros')
    success_message = "Libro Creado Satisfactoriamente"


class LibrosEdit(Sinprivilegios, generic.UpdateView):
    permission_required = "libreria.change_libros"
    model = Libros
    template_name= "libreria/libros_form.html"
    context_object_name = "obj"
    form_class = LibrosForm
    success_url = reverse_lazy('lib:libros')
    success_message = "Libro Actualizado Satisfactoriamente"


class LibrosDel(Sinprivilegios, generic.DeleteView):
    permission_required = "libreria.delete_libros"
    model = Libros
    template_name = "libreria/libreria_del.html"
    context_object_name = "obj"
    success_url = reverse_lazy('lib:libros')
    success_message = "Libro Eliminado Satisfactoriamente"


def listar_categorias(request):
    busqueda = request.POST.get("buscar")
    categorias = Categorias.objects.all()

    if busqueda:
        categorias = Categorias.objects.filter(
            Q(id_categoria__icontains = busqueda) | 
            Q(categoria__icontains = busqueda) 
        ).distinct()
         
    return render(request, 'libreria/categorias_list.html', {'categorias': categorias})

class CatgeoriasNew(Sinprivilegios, generic.CreateView):
    permission_required = "libreria.add_categorias"
    model = Categorias
    template_name = "libreria/categorias_form.html"
    context_object_name = "obj"
    form_class = CategoriasForm
    success_url = reverse_lazy('lib:categorias')
    success_message = "Categoria Creada Satisfactoriamente"


class CategoriaEdit(Sinprivilegios, generic.UpdateView):
    permission_required = "libreria.change_categorias"
    model = Categorias
    template_name = "libreria/categorias_form.html"
    context_object_name = "obj"
    form_class = CategoriasForm
    success_url = reverse_lazy('lib:categorias')
    success_message = "Categoria Actualizada Satisfactoriamente"


class CategoriaDel(Sinprivilegios, generic.DeleteView):
    permission_required = "libreria.delete_categorias" 
    model = Categorias
    template_name = "libreria/libreria_del.html"
    context_object_name = "obj"
    success_url = reverse_lazy('lib:categorias')
    success_message = "Categoria Eliminada Satisfactoriamente"


@login_required(login_url='/login/')
@permission_required('libreria.view_clientes', login_url='lib:sin_privilegios')
def listar_clientes(request):
    busqueda = request.POST.get("buscar")
    clientes = Clientes.objects.all()

    if busqueda:
        clientes = Clientes.objects.filter(
            Q(id_clientes__icontains = busqueda) | 
            Q(identificacion__icontains = busqueda) |
            Q(nombres__icontains = busqueda) |
            Q(apellidos__icontains = busqueda) |
            Q(telefono__icontains = busqueda) |
            Q(direccion__icontains = busqueda) 
        ).distinct()
         
    return render(request, 'libreria/clientes_list.html', {'clientes': clientes})


class ClientesNew(Sinprivilegios, generic.CreateView):
    permission_required = "libreria.add_clientes"
    model = Clientes
    template_name = "libreria/clientes_form.html"
    context_object_name = "obj"
    form_class = ClientesForm
    success_url = reverse_lazy('lib:clientes')
    success_message = "Cliente Creado Satisfactoriamente"


class ClientesEdit(Sinprivilegios, generic.UpdateView):
    permission_required = "libreria.change_clientes"
    model = Clientes
    template_name = "libreria/clientes_form.html"
    context_object_name = "obj"
    form_class = ClientesForm
    success_url = reverse_lazy('lib:clientes')
    success_message = "Cliente Actualizado Satisfactoriamente"


class ClientesDel(Sinprivilegios, generic.DeleteView):
    permission_required = "libreria.delete_clientes" 
    model = Clientes
    template_name = "libreria/libreria_del.html"
    context_object_name = "obj"
    success_url = reverse_lazy('lib:clientes')
    success_message = "Categoria Eliminada Satisfactoriamente"


def listar_libros_por_autor(request):
    busqueda = request.POST.get("buscar")
    librosXautor = LibrosPorAutor.objects.all()

    if busqueda:
        librosXautor = Categorias.objects.filter(
            Q(id_autor__exact  = busqueda) | 
            Q(idbn__exact = busqueda) 
        ).distinct()
         
    return render(request, 'libreria/libros_por_autor_list.html', {'librosXautores': librosXautor})


class LibrosPorAutorNew(Sinprivilegios, generic.CreateView):
    permission_required = "libreria.add_librosporautor"
    model = LibrosPorAutor
    template_name = "libreria/libros_por_autor_form.html"
    context_object_name = "obj"
    form_class = LibrosPorAutorForm
    success_url = reverse_lazy('lib:libros_por_autor')
    success_message = "Libro Por Autor Creado Correctamente"


class LibrosPorAutorEdit(Sinprivilegios, generic.UpdateView):
    permission_required = "libreria.change_librosporautor"
    model = LibrosPorAutor
    template_name = "libreria/libros_por_autor_form.html"
    context_object_name = "obj"
    form_class = LibrosPorAutorForm
    success_url = reverse_lazy('lib:libros_por_autor')
    success_message = "Libro Por Autor Actualiado Correctamente"


class LibrosPorAutorDel(Sinprivilegios, generic.DeleteView):
    permission_required = "libreria.delete_librosporautor"
    model = LibrosPorAutor
    template_name = "libreria/libreria_del.html"
    context_object_name = "obj"
    success_url = reverse_lazy('lib:libros_por_autor')
    success_message = "Autor Eliminado Satisfactoriamente"


@login_required(login_url='/login/')
@permission_required('libreria.view_pedidoscliente', login_url='lib:sin_privilegios')
def listar_pedidos_clientes(request):
    busqueda = request.POST.get("buscar")
    pedidos_clientes = PedidosCliente.objects.all()

    if busqueda:
        pedidos_clientes = PedidosCliente.objects.filter(
            Q(nro_pedido__icontains = busqueda) | 
            # Q(id_cliente__exact = busqueda) |
            # Q(isbn__exact = busqueda) |
            Q(fecha_pedido__icontains = busqueda) | 
            Q(cantidad__icontains = busqueda) | 
            Q(valor__icontains = busqueda) 
        ).distinct()
         
    return render(request, 'libreria/pedidosclientes_list.html', {'pedidos_clientes': pedidos_clientes})

# Funciones de carrito de compras
def cart_add(request, isbn):
    cart = Cart(request)
    libro = Libros.objects.get(isbn=isbn)
    cart.add(libro=libro)
    return redirect("lib:libros")

def item_clear(request, isbn):
    cart = Cart(request)
    libro = Libros.objects.get(isbn=isbn)

libreria/templates/libreria/carro.html
{% extends 'prjaprendizjbhm/base.html' %} {% block section %}
{% load carro_tag %}
<div>
    <br>
    <div class="container">
    <div id="carrito_compras" class="col-md-12">
        <center>
            <h1>
                Mi carrito de compras, Cantidad de productos : {{request.session.cart|length}}
            </h1>
        </center>
	<table id="cart" class="table table-hover table-condensed">
        <thead>
            <tr>
                <th style="width:38%">Libros</th>
                <th style="width:10%">Precio</th>
                <th style="width:8%">Cantidad</th>
                <th style="width:18%" class="text-center">Subtotal</th>
                <th style="width:16%">Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for key,value in request.session.cart.items %}
            <tr>
                <td data-th="Product">
                    <div class="row">
                        <div class="col-sm-2 hidden-xs"><img src="{{value.image}}" alt="..." class="img-responsive"></div>
                        <div class="col-sm-10">
                            <h4 class="nomargin">Titulo: </h4>
                            <p> {{value.name}}</p>
                        </div>
                    </div>
                </td>
                <td data-th="Price">{{value.price}}</td>
                <td data-th="Quantity">
                    <input type="number" class="form-control text-center" value="{{value.quantity}}">
                </td>
                <td data-th="Subtotal" class="text-center">{{ value.price|multiply:value.quantity }}</td>
                <td class="actions" data-th="">
                    <a href="{% url 'lib:item_increment' value.product_id %}" class="btn btn-primary btn-sm"><i class="zmdi zmdi-plus"></i></i></a>
                    <a href="{% url 'lib:item_decrement' value.product_id %}" class="btn btn-danger btn-sm"><i class="zmdi zmdi-minus"></i></i></a>
                    <a href="#" class="btn btn-info btn-sm"><i class="zmdi zmdi-refresh"></i></a>
                    <a href="{% url 'lib:item_clear' value.product_id %}" class="btn btn-danger btn-sm"><i class="zmdi zmdi-close"></i></a>								
                </td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <td><a href="{% url 'lib:libros' %}" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continuar Comprando</a></td>
                <td><a href="{% url 'lib:cart_clear' %}" class="btn btn-danger"><i class="fa fa-angle-left"></i> Vaciar carro de compras</a></td>
                <td colspan="1" class="hidden-xs"></td>
                <td class="hidden-xs text-center"><strong>{{ cart_total_amount }}</strong></td>
                <td><a href="#" class="btn btn-success btn-block">Comprar <i class="fa fa-angle-right"></i></a></td>
            </tr>
        </tfoot>
    </table>
    </div>
</div>

{% endblock section %}

{% block js_page %}

{% endblock js_page %}

libreria/templates/libreria/clientes_form.html
{% extends 'prjaprendizjbhm/base.html' %} {% block section %} {% load static %}

<body>
    <div class="container-fluid" style="margin: 50px 0;">
        <div class="row">
            <div class="col-xs-12 col-sm-4 col-md-3">
                <img src="{% static 'prjaprendizjbhm/assets/img/user01.png' %}" alt="user" class="img-responsive center-box" style="max-width: 110px;">
            </div>
            {% if obj %}
            <div class="col-xs-12 col-sm-8 col-md-8 text-justify lead">
                Bienvenido a la sección para actualizar clientes del sistema, puedes editar los campos que desees del siguiente formulario 
            </div>
            {% else %}
            <div class="col-xs-12 col-sm-8 col-md-8 text-justify lead">
                Bienvenido a la sección para registrar nuevos clientes al sistema, debes de llenar todos los campos del siguiente formulario para registrar un cliente
            </div>
            {% endif %}
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12 lead">
                <ol class="breadcrumb">
                    <li class="active">Nuevo Cliente</li>
                    <li><a href="{% url 'lib:clientes' %}">Listado de Clientes</a></li>
                </ol>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="container-flat-form">
            {% if obj %}
            <div class="title-flat-form title-flat-red">Actualizar CLiente</div>
            {% else %}
            <div class="title-flat-form title-flat-blue">Registrar un Cliente</div>
            {% endif %}
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
                        <div class="group-material">
                            <input type="number" class="material-control tooltips-general" name="identificacion" id="id_identificacion" placeholder="Ingrese la Identificacion del Cliente" required="" maxlength="12" data-toggle="tooltip" data-placement="top" title="Escribe la Identificacion del Cliente"
                            value="{% if obj %}{{ obj.identificacion }}{% endif %}">
                            <span class="highlight"></span>
                            <span class="bar"></span>
                            <label>Identificacion</label>
                        </div>
                        <div class="group-material">
                            <input type="text" class="material-control tooltips-general" name="nombres" id="id_nombres" placeholder="Nombres del Cliente" required="" maxlength="25" pattern="[a-zA-ZáéíóúÁÉÍÓÚñÑ ]{1,70}" data-toggle="tooltip" data-placement="top" title="Escribe los nombres del Cliente"
                            value="{% if obj %}{{ obj.nombres }}{% endif %}">
                            <span class="highlight"></span>
                            <span class="bar"></span>
                            <label>Nombres</label>
                        </div>
                        <div class="group-material">
                            <input type="text" class="material-control tooltips-general" name="apellidos" id="id_nombres" placeholder="Apellidos del Cliente" required="" maxlength="25" pattern="[a-zA-ZáéíóúÁÉÍÓÚñÑ ]{1,70}" data-toggle="tooltip" data-placement="top" title="Escribe los Apellidos del Cliente"
                            value="{% if obj %}{{ obj.apellidos }}{% endif %}">
                            <span class="highlight"></span>
                            <span class="bar"></span>
                            <label>Apellidos</label>
                        </div>
                        <div class="group-material">
                            <input type="number" class="material-control tooltips-general" name="telefono" id="id_telefono" placeholder="Telefono" required=""  maxlength="12" data-toggle="tooltip" data-placement="top" title="Ingresa el Telefono del Cliente"
                            value="{% if obj %}{{ obj.telefono }}{% endif %}">
                            <span class="highlight"></span>
                            <span class="bar"></span>
                            <label>Telefono</label>
                        </div>
                        <div class="group-material">
                            <input type="text" class="material-control tooltips-general" name="direccion" id="id_direccion" placeholder="Direccion del Cliente"  maxlength="128" data-toggle="tooltip" data-placement="top" title="Ingrese la Direccion del Cliente"
                            value="{% if obj %}{{ obj.direccion }}{% endif %}">
                            <span class="highlight"></span>
                            <span class="bar"></span>
                            <label>Direccion</label>
                        </div>
                        <div class="group-material">
                            <input type="email" class="material-control tooltips-general" name="correo_electronico" id="id_correo_electronico" placeholder="Email del Cliente" maxlength="128" data-toggle="tooltip" data-placement="top"  title="ingrese El correo electronico del Cliente"
                            value="{% if obj %}{{ obj.correo_electronico }}{% endif %}">
                            <span class="highlight"></span>
                            <span class="bar"></span>
                            <label>Email</label> 
                        </div>
                        <!-- {{ forms.as_p }} -->
                        <p class="text-center">
                            <button type="reset" class="btn btn-info" style="margin-right: 20px;"><i class="zmdi zmdi-roller"></i> &nbsp;&nbsp; Limpiar</button>
                            <button type="submit" class="btn btn-primary" style="margin-right: 20px;"><i class="zmdi zmdi-floppy"></i> &nbsp;&nbsp; Guardar</button>
                            <a href="{% url 'lib:clientes' %}" class="btn btn-success"><span class="zmdi zmdi-fullscreen-exit"></span> &nbsp;&nbsp; Cancelar </a>
                        </p>
                    </div>
                </div>
            </form>
        </div>
    </div>
</body>

</html>

{% endblock section %}

libreria/templates/libreria/libreria_del.html
{% extends 'prjaprendizjbhm/base.html' %} {% block section %} {% load static %}

<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-4 col-md-7 mb-6">
        <div class="card border-left-danger shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-4">
                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">¿Estás seguro de Eliminar este elemto?</div>
                        <button type="submit" class="btn btn-danger">Si, Eliminar</button>
                        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                    </div>
                    <div class="col-auto">
                        <i class="far fa-question-circle fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</form>
{% endblock section %}

{% block js_page %} 
{% endblock js_page %}

libreria/templates/libreria/sin_privilegios.html
{% extends 'prjaprendizjbhm/base.html' %} {% block section %}
<div>
    <div class="card border-left-danger shadow h-100 py-2">
        <div class="card-body">
            <div class="text-xs font-weight-bold text-primary text-uppercase mb-2">
                Usuario: <mark>{{ user.username }} --  identificado como {{ user.get_full_name }}</mark>
            </div>
            <div class="dropdown-divider"></div>

            <div class="div">
                <mark>No tienen suficientes privilegios</mark> para cargar opción solicitada.
                <br>
                <small>Para poder acceder, debes loguearte con usuario con privilegios necesario</small>
                        
            </div>
            <div class="dropdown-divider"></div>
            <div class="row">
                <div class="col">
                    <a href="{% url 'lib:home' %}" class="btn btn-success"><span class="fa fa-home"></span>Ir a inicio</a>
                    <a href="{% url 'lib:login' %}" class="btn btn-success"><span class="fa fa-user"></span>Ingresar con otro usuario</a>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock section %}